# ------------------------------------------------------------------------------
# Compile the code
FROM ubuntu:focal AS build
ADD Mark1 /src/Mark1
ADD common /src/common
WORKDIR /src/Mark1
RUN apt-get update && \
    apt-get install -y build-essential libgcrypt20-dev libzmq3-dev && \
    ./compile.sh

# ------------------------------------------------------------------------------
# Pull base image
FROM ubuntu:focal
MAINTAINER Brett Kuskie <fullaxx@gmail.com>

# ------------------------------------------------------------------------------
# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# ------------------------------------------------------------------------------
# Install libgcrypt,libzmq and clean up
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgcrypt20 libzmq5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Install scripts and configuration files
COPY --from=build /src/Mark1/app/tpad.sh /app/    
COPY --from=build /src/Mark1/tpad.exe /app/

# ------------------------------------------------------------------------------
# Identify Volumes
VOLUME /tpad
VOLUME /log

# ------------------------------------------------------------------------------
# Expose ports
EXPOSE 8480
EXPOSE 8471
EXPOSE 8468

# ------------------------------------------------------------------------------
# Define default command
CMD ["/app/tpad.sh"]
