# ------------------------------------------------------------------------------
# Compile the code
FROM ubuntu:focal AS build
ADD Mark2 /src/Mark2
ADD common /src/common
WORKDIR /src/Mark2
RUN apt-get update && \
    apt-get install -y build-essential libgcrypt20-dev libzmq3-dev && \
    ./compile.sh

# ------------------------------------------------------------------------------
# Pull base image
FROM ubuntu:focal
MAINTAINER Brett Kuskie <fullaxx@gmail.com>

# ------------------------------------------------------------------------------
# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# ------------------------------------------------------------------------------
# Install libgcrypt,libzmq and clean up
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgcrypt20 libzmq5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Install scripts and configuration files
COPY app/absorb_mk2.sh /app/    
COPY --from=build /src/Mark2/absorb.exe /app/

# ------------------------------------------------------------------------------
# Identify Volumes
VOLUME /absorb
VOLUME /log

# ------------------------------------------------------------------------------
# Define default command
CMD ["/app/absorb_mk2.sh"]
